name: Deploy site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run deploy
